ZipArchive/ZipArchive

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m, Tests/SSZipArchiveTests.m
This adds a zipArchiveShouldUnzipFileAtIndex, which is called before
each call to zipArchiveWillUnzipFileAtIndex, allowing a delegate to
cancel the unzip progress.
Originally I thought this was unnecessary due to https://github.com/soffes/ssziparchive/pull/61 but that one is for zipping, this is for unzipping.
=> Add a delegate for cancelling unzips

SSZipArchive/minizip/ioapi.c
I understand this file is originally part of MiniZip, but I think it would still be nice to fix the warning.
Duplicate of https://github.com/soffes/ssziparchive/issues/82
```
SSZipArchive/minizip/ioapi.c:195:33: Implicit conversion loses integer precision: 'ZPOS64_T' (aka 'unsigned long long') to 'long'
```
=> Fix implicit conversion warning

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
Hi.
I came across this due to warnings on loss of precision in implicit type conversions in Xcode 6.
I'm not 100% happy with this patch as I have changed the type in the delegate call. However the file size returned by `-[NSFileManager attributesOfItemAtPath:error:]` is of type `unsigned long long`.
One could argue that it is pretty unlikely to exceed the range of `NSInteger` but this way it is consistent with the type returned by NSFileManager.
If you think it's not worth changing the delegate call declaration I'm happy to add casts to (NSInteger) to silence the warnings.
=> Report file size as unsigned long long to delegate

SSZipArchive.m
In SSZipArchive.m:L377, writeFileAtPath opens a file handle but never closes it:
```objective-c
- (BOOL)writeFileAtPath:(NSString *)path withFileName:(NSString *)fileName {
NSAssert((_zip != NULL), @"Attempting to write to an archive which was never opened");
FILE *input = fopen([path UTF8String], "r");
if (NULL == input) {
return NO;
}
```
This needs to call fclose if fopen succeeds
=> writeFileAtPath does not close file handle

SSZipArchive.h, SSZipArchive.m, SSZipArchive.podspec, Tests/CollectingDelegate.h, Tests/CollectingDelegate.m, Tests/SSZipArchive.xcodeproj/project.pbxproj, Tests/SSZipArchiveTests.m
Currently the delegate methods send a file_info structure that provides some context for what has just been unzipped. But it does not provide the name of the file that was unzipped. I have added a delegate method that does report the name of the file so that the receiver can perform and tasks that are needed for that file.
=> Add a delegate method that includes the filePath of newly extracted files

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
For my app, I needed a way to send all types of data, including file packages. Since these are technically directories, I needed to compress them in order to obtain an NSData blob for them. However, when compressing directories using SSZipArchive, it only enumerates the contents of the directory and adds them to the zip archive individually, which means upon unzipping the file all the individual files are unzipped, rather than the package as a complete unit.
This pull request adds the ability to keep the parent directory when compressing a directory. Essentially, when the provided keepParentDirectory parameter is YES, I prefix all relative file paths with the parent directory, so upon unzipping the parent directory (or package) remains a complete until, with its subfiles contained within …
=> Added option to keep parent directory when compressing directory contents

SSZipArchive/minizip/unzip.c
Removing the clang analyzer silencer in these lines fixed another clang analyzer warning that appeared in line 1534.
In addition these lines do not cause a static analyzer warning in latest Xcode any longer.
Tested with Xcode 5.0.2
=> Fix clang analyzer warning appearing in line 1534

SSZipArchive/SSZipArchive.m
The warning that is fixed by this #ifdef is also appearing on OSX 10.10 build targets.
The macro is working, but also explicitly checking for OSX 10.10 feels a bit more clean to me, so it's up to you :)
=> Fix calendar deprecation warning on OSX 10.10

SSZipArchive/minizip/unzip.c
This popped up as a warning. The variable seems to be unused afterwards anyway, but this is the smallest change I could come up with.
=> Avoid shadowing variable when extracting ZIP64 extra header fields

SSZipArchive.podspec
This is an update of podspec file to point to tag v1.0.0. Currently is pointing to an old tag that is not referencing to the last commit from master branch. If you approve this PR you must create a tag v1.0.0 pointing to the last commit from master branch in order to have the latest changes from ssziparchive. In addition you should submit this podspec update to the podspecs repository.
Currently in cocoapods, the podfile is pointing to version 1.0 but there is no such a Tag.
=> PodSpec update

ZipArchive/Main.m
When adding files to an archive, the file pointer was being left open.
This was preventing adding large numbers of files to an archive.
=> Close file pointer after adding to archive

SSZipArchive/SSZipArchive.m, SSZipArchive/minizip/zip.c
There are couple of places in the code where the result of malloc() function is not being checked to be sure it is correct (not NULL) before use.
In our project we now must send every build for the Veracode analysis. The tool scans your binary for different kinds of security flaws, including the ones related to malloc().
My changes add checks for the return values of the malloc() function where it's not safe to use it if the result is NULL.
=> Mitigate potential memory-allocation related flaws 

SSZipArchive/SSZipArchive.m
There are a few places in the unzip process where it short circuits with a `return NO` without setting `*error` or invoking the complete block. This fixes one of them when a crc check fails.
=> error properly when crc check fails

.gitignore, README.md, SSZipArchive/SSZipArchive.h, SwiftExample/Cartfile, SwiftExample/SwiftExample.xcodeproj/project.pbxproj, SwiftExample/SwiftExample/ViewController.swift
I've added Carthage to a new target on the example project. Carthage does not support building from local files the same way cocoapods does. So in order to test carthage is building before merging this PR you must make one of the following changes:
```
github "GWStuartClift/ZipArchive" "carthage-support"
```
1. Navigate to the root directory
2. Run `carthage build --no-skip-current --platform ios`
3. Open the SwiftExample and using the `SwiftExampleCarthage` target; remove current framework and re-link with the framework at `../Carthage/Build/iOS/ZipArchive.framework`
4. Go to the *run script* phase and change the path of the input file to `$(SRCROOT)/../Carthage/Build/iOS/ZipArchive.framework`
The module name for this project is `ZipArchive` however, the pod spec is listed as …
=> Fix Carthage support

SSZipArchive/SSZipArchive.m
Hi guys!
As far as I can see, current version of ZipArchive doesn't handle cases and errors related to filled storage on the devices. It reports that unzipping was succeed, but is actually wrong. 
I have handled two places where we can get errors related to filled storage.
=> Run out of space issue

SSZipArchive/SSZipArchive+Swift.swift, SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m, ZipArchive.xcodeproj/project.pbxproj
I've taken the liberty of adding the nullability annotations to the library to make it a little more compatible with Swift. All parameters of all functions are assumed to be not nullable except where noted. When used in a Swift project the developer should no longer see every parameter of every method as forced unwrapped. This should lead to safer code in both Objective-C and Swift when using this framework.
The only code breaking change I needed to make was in `+ (BOOL)unzipFileAtPath:(NSString *)path toDestination:(NSString *)destination overwrite:(BOOL)overwrite password:(nullable NSString *)password error:(NSError * *)error delegate:(nullable id<SSZipArchiveDelegate>)delegate`. I swapped the error and delegate parameters so the method now reads as:
`+ (BOOL)unzipFileAtPath:(NSString …
=> Nullablilty Annotations

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
Our application highly relies on SSZipArchive, so sincere thanks to all contributors and maintainers!
Recently our archives became relatively large for mobile devices and we encountered performance issues in unzipping process. I've spent some time in profiler and returned with 2 bottlenecks:
1. Operations with file attributes
2. NSMutableSet for storing these file attributes
I've made tests with one of my production archive, it contains ~6300 files and takes ~60mb.
Here is the results of unzipping performance comparison:
Collection | Performance
-----------|--------------
NSMutableSet | 55s
NSMutableArray | 20s
No attributes | 9s
1. 0820787 - Make operations with attributes optional.
Not everyone needs that zipped files' attributes match to the unzipped, especially with this price. So …
=> Performance improvements

SSZipArchive/SSZipArchive.m
for the issure #269 
the demo will show the bug,when zip file include chinese dirname or filename,UnZip will be ignored them.
[UnZip-Demo.zip](https://github.com/ZipArchive/ZipArchive/files/410466/UnZip-Demo.zip)
=> if filename contains chinese dir transform Encoding

SSZipArchive/SSZipArchive+Swift.swift, ZipArchive.xcodeproj/project.pbxproj
Hi,
this is fix #276 for Carthage build on XCode 8 & Swift 3 conversion. I didn't see that there has already been pull request for #280, this patch should do the same with minimal changes to the xcproject file.
Both patches will allow Carthage builds.
Pavel
=> Convert Swift code in to Swift 3 and change appropriate project settings

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
Exposing completionHandler's NSError * as optional Error? in Swift3 rather than Error. Without it calling completion handler in Swift crashes the app.
=> Define NSError as nullable argument of completionHandler

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
Currently the error domain string and it's possible code values are magic strings/numbers inside the .m files. Whenever someone from the outside needs to check and compare with them it's required to manually write down these values in the own project. The danger here arises when these values change in the library and the corresponding values in an own project are not adjusted.
By defining the error domain string and code values as public constants or an enum we can use the exact same values from the outside as used within and additionally whenever the enum is extended by additional new cases any switch statement without default-case will produce a warning about a new case.
=> Public constants for error domain and error codes

SSZipArchive/minizip/unzip.c
I believe this comma should be a semicolon, since this looks like a full statement, and there's no reason to want the comma operator here as far as I can see.
=> Replace comma with semicolon

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
As I wrote in my comment on #322, some error codes are used elsewhere
=> same FailedOpen error code is used for other files too

SSZipArchive/SSZipArchive.m
This would grant read+write to all uncompressed files to solve #293. An alternative way to implement it would be to make it an option.
=> adding read+write permissions

SSZipArchive/SSZipArchive.m
Without these changes existing symlinks will not be overwritten, reagrdless of what `overwrite` is set to. `symlink()` returns an error code of `17`, defined in `/usr/include/sys/errno.h` as
```c
#define    EEXIST        17        /* File exists */
```
These errors are now also bubbled up instead of simply being logged.
=> Added support for overwriting existing symlinks

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
Passing zero length paths into the Swift interface causes an uncaught exception.
Longer term I'd like to guard in the Swift against anything that Objective-C might throw, but this should handle the problem for now while providing a specific error for invalid input.
=> Handle zero-length arguments

SSZipArchive/SSZipArchive.m
Local variable named success conflicts with outer success variable.  
This results in a 'Value stored in success is never read' issue when running Analyze in Xcode
=> Fixes Analyze issue for success variable

SSZipArchive/SSZipArchive.m
and preventing multiple calls to `close` by setting _zip to nil
=> returning write errors on close

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
__IPHONE_8_0 is always defined on Xcode 7 and above.
__nullable was replaced by _Nullable starting Xcode 7.
=> readability and simplifications

ObjectiveCExample/ObjectiveCExample/ViewController.m, ObjectiveCExample/Podfile.lock, SSZipArchive.podspec, SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m, SSZipArchive/minizip/zip.c, SSZipArchive/minizip/zip.h, SwiftExample/Podfile.lock, SwiftExample/SwiftExample/ViewController.swift
To be reviewed after https://github.com/ZipArchive/ZipArchive/pull/392 is merged.
This should fix one of the last known bug of ZipArchive (known left bugs to me are potentially # 313 and # 380). ✌️ 
As a tradition, we're skipping number 9 and we're going from 2.0.8 to 2.1.0... well, we're actually following semantic versioning and this pull request is feature additive. 😃 
Fix #228 and #369.
=> Optional aes and custom compression level

ObjectiveCExample/ObjectiveCExample/ViewController.m, ObjectiveCExample/Podfile.lock, SSZipArchive.podspec, SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m, SSZipArchive/minizip/zip.c, SSZipArchive/minizip/zip.h, SwiftExample/Podfile.lock, SwiftExample/SwiftExample/ViewController.swift
To be reviewed after #393.
Change the default behavior to NOT unzip nested zip files, but allow to do it with the nestedZipLevel parameter.
Fix #319
=> Nested zip level

ObjectiveCExample/ObjectiveCExampleTests/SSZipArchiveTests.m, SSZipArchive/SSZipArchive.m
currentFileNumber needs to be incremented even if we `continue`
=> ignoring __MACOSX/

SSZipArchive/minizip/unzip.c
#391 was breaking #36 sample.
This is a better fix.
=> hotfix for #391

SSZipArchive/SSZipArchive.m
Apple's API description:
`- (NSArray<NSString *> *)subpathsOfDirectoryAtPath:(NSString *)path error:(NSError * _Nullable *)error;`
> Performs a deep enumeration of the specified directory and returns the paths of all of the contained subdirectories.
> Because this method recurses the directory’s contents, you might not want to use it in performance-critical code. 
`- (NSArray<NSString *> *)contentsOfDirectoryAtPath:(NSString *)path error:(NSError * _Nullable *)error;`
> Performs a shallow search of the specified directory and returns the paths of any contained items.
=> optimization, perform a shallow search instead of a deep enumeration

ObjectiveCExample/ObjectiveCExampleTests/SSZipArchiveTests.m, SSZipArchive/SSZipArchive.m
This is a follow up to my review on #456 and the issues I found on 28th August 2018.
* improve security by dealing with "." and "..", preventing permissions override
* fix Unicode support in folder names
=> File path sanitation compatible with Unicode

SSZipArchive/SSZipArchive.m
issue: It will not return an error even if unzip fails because of exceeding of the limit of file open number of process. #481
Here is a solution of the issue.
=> A solution of #481 (error handling when exceeding the limit of file open)

ZipArchive.xcodeproj/project.pbxproj
When trying Carthage v2.2.1, there will have include error that missing `SSZipCommon.h`
I checked that inside Carthage built framework header folder there doesn't have SSZipCommon.h, so I put it back and it fixed the build issue
=> Fix Carthage not see SSZipCommon.h

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
This method computes the total payload size which can be useful
if you are pre-flighting data or setting up a progress bar.
=> Added -payloadSizeForArchiveAtPath:

SSZipArchive/SSZipArchive.m
The message is appropriate whether we fail on the first, second or nth
file in the archive.
Something that came up in our internal code review :-)
=> Improved error message

SSZipArchive/SSZipArchive.m
Fix the problem that ZipArchive compressed special characters decompressed by7zip or WinRAR, display garbled characters. Because unicode bit added by PKZIP higher version is not set in the zip file header.
=> Fix garbled characters when decompressing by third-party tools.

SSZipArchive/SSZipArchive.m
If archive file are included in `directoryPath` when creating archive file, it will result in self-compressing, overload of CPU. So we forbid that by adding path judgement.
=> Forbid archive included in compress path

Example/ObjectiveCExample/ViewController.m, Example/ObjectiveCExampleTests/CancelDelegate.h, Example/ObjectiveCExampleTests/CollectingDelegate.h, Example/ObjectiveCExampleTests/ProgressDelegate.h, Example/ObjectiveCExampleTests/SSZipArchiveTests.m, Example/SwiftExample/ViewController.swift, Example/SwiftExample_macOS/ViewController.swift, README.md, SSZipArchive.podspec
Bump verison to 2.3.0, move headers in example projects to use ZipArchive.h headers and update readme to include SPM
=> 2.3.0 - version bump, header updates, readme update

Example/ObjectiveCExampleTests/SSZipArchiveTests.m, SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
This should fix issue #492 . Implementing the suggestion by @Coeur to expose the usage of APPEND_STATUS_ADDINZIP instead of APPEND_STATUS_CREATE for support appending to existing zip files.
=> #492.appending to zip

SSZipArchive.podspec, SSZipArchive/include/ZipArchive.h
My project can not run. Import modes is not correct.
=> Matches different import modes

Package.swift
Without an explicit Mac Catalyst deployment target to match the macOS target, the prior minimum OS version bump breaks the build for Catalyst apps targeting macOS 10.15 and macOS 11 (which I guess are already covered by the security patch for [CVE-2018-25032](https://nvd.nist.gov/vuln/detail/cve-2018-25032)?). Mac apps generally need to target further back than the latest OS.
Could make sense to increase this from `.macCatalyst("13.0")` to a higher point release to be sure. Thoughts?
=> Fixes Mac Catalyst build with bumped OS minimum requirements

Package.swift, SSZipArchive.podspec, SSZipArchive/Supporting Files/PrivacyInfo.xcprivacy, ZipArchive.xcodeproj/project.pbxproj
Added app privacy file for File Timestamp API. 
These are the list of APIs that require reason:
[creationDate](https://developer.apple.com/documentation/foundation/fileattributekey/1418187-creationdate)
[modificationDate](https://developer.apple.com/documentation/foundation/fileattributekey/1410058-modificationdate) 
[stat](https://developer.apple.com/documentation/kernel/stat)
`lstat(_:_:)`
Given the reason as `C617.1: Inside app or group container, per documentation`
Quoting from Apple's documentation,
> C617.1
> Declare this reason to access the timestamps of files inside the app container, app group container, or the app’s CloudKit container.
=> add privacy manifest as per apple's new guidelines

.github/workflows/actions.yml, Example/Podfile, Example/Podfile.lock, Example/ZipArchiveExample.xcodeproj/project.pbxproj, Example/ZipArchiveExample.xcodeproj/xcshareddata/xcschemes/ObjectiveCExample_visionOS.xcscheme, Example/ZipArchiveExample.xcodeproj/xcshareddata/xcschemes/ObjectiveCExample_watchOS.xcscheme, Package.swift, README.md, SSZipArchive.podspec, SSZipArchive/Supporting Files/PrivacyInfo.xcprivacy, ZipArchive.xcodeproj/project.pbxproj, ZipArchive.xcodeproj/xcshareddata/xcschemes/ZipArchive-visionos.xcscheme
Two small "breaking" changes:
1. Swift minimum version goes from 5.5 to 5.9 for visionOS support in Package.Swift
2. PrivacyInfo reason modified from C617.1 (only files inside the app container) to 0A2A.1 (any files, we're a third-party SDK): https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
Hence, bumping version to ZipArchive 2.6.0.
=> Adding visionOS

.github/workflows/actions.yml, Example/ZipArchiveExample.xcodeproj/xcshareddata/xcschemes/ObjectiveCExample_iOS.xcscheme, Example/ZipArchiveExample.xcodeproj/xcshareddata/xcschemes/ObjectiveCExample_tvOS.xcscheme, Example/ZipArchiveExample.xcodeproj/xcshareddata/xcschemes/ObjectiveCExample_visionOS.xcscheme, Example/ZipArchiveExample.xcodeproj/xcshareddata/xcschemes/ObjectiveCExample_watchOS.xcscheme, Example/ZipArchiveExample.xcodeproj/xcshareddata/xcschemes/SwiftExample_iOS.xcscheme
GitHub Actions only supports macOS 12+ now:
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
Also modernising the iOS/tvOS/visionOS/watchOS schemes because Apple requires modern Xcode anyway for those: https://developer.apple.com/ios/submit/
I'm leaving the Carthage scheme untouched, as I don't maintain it.
=> Moving GitHub actions from macOS 11 to 12

ZipArchive.xcodeproj/xcshareddata/xcschemes/ZipArchive-iOS.xcscheme, ZipArchive.xcodeproj/xcshareddata/xcschemes/ZipArchive-tvos.xcscheme, ZipArchive.xcodeproj/xcshareddata/xcschemes/ZipArchive-visionos.xcscheme, ZipArchive.xcodeproj/xcshareddata/xcschemes/ZipArchive-watchos.xcscheme
Modernising the iOS/tvOS/visionOS/watchOS schemes because Apple requires modern Xcode anyway for those: https://developer.apple.com/ios/submit/
I'm leaving the macOS scheme untouched, for older Xcodes.
=> Modernising iOS/tvOS/visionOS/watchOS schemes

Example/ObjectiveCExampleTests/SSZipArchiveTests.m, SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
`withContentsOfDirectory:` should return error when parameter isn't a directory
`withFilesAtPaths:` should not write a file when parameter is a directory
Fix: #621
@597579501
=> Support directory and non-directory parameters

SSZipArchive/SSZipCommon.h
I accidentally re-added tmu_date in #724 when it is not needed
=> removing tmu_date

SSZipArchive/SSZipArchive.h, SSZipArchive/SSZipArchive.m
Fix #619
Fix #626
Fix #693
(Maybe fix #685)
Supersedes #640
Some backstory.
The [legacy minizip](https://github.com/madler/zlib/blob/develop/contrib/minizip/zip.h) had variants up to `zipOpenNewFileInZip4_64`. And minizip-ng is a better drop-in replacement to it.
On 8 October 2017, I added `zipOpenNewFileInZip5` in ZipArchive #393 and in minizip-ng 1.2 https://github.com/zlib-ng/minizip-ng/pull/182 with the extra parameter `int aes` for **optional** aes.
On 9 October 2017, nathan added `zipOpenNewFileInZip5` in minizip-ng 2.0.0 in:
https://github.com/zlib-ng/minizip-ng/commit/8db28c9afef013c426f76b3109b8ba94c51f359f, but with the same signature as `zipOpenNewFileInZip4_64` instead of the required signature I had created a day before. :(
Since then, we kept in ZipArchive a custom version …
=> fix zip64 logic based on missing uncompressed_size

Example/ObjectiveCExampleTests/SSZipArchiveTests.m, SSZipArchive/SSZipArchive.m, SSZipArchive/minizip/compat/ioapi.c, SSZipArchive/minizip/compat/unzip.h, SSZipArchive/minizip/compat/zip.h, SSZipArchive/minizip/mz.h, SSZipArchive/minizip/mz_os.c, SSZipArchive/minizip/mz_os.h, SSZipArchive/minizip/mz_os_posix.c, SSZipArchive/minizip/mz_strm.c, SSZipArchive/minizip/mz_strm_buf.c, SSZipArchive/minizip/mz_strm_os_posix.c, SSZipArchive/minizip/mz_strm_pkcrypt.c, SSZipArchive/minizip/mz_strm_split.c, SSZipArchive/minizip/mz_strm_zlib.c, SSZipArchive/minizip/mz_zip.c, SSZipArchive/minizip/mz_zip_rw.c
Updating minizip to 4.0.9.dev (https://github.com/zlib-ng/minizip-ng/pull/867)
Fix #731
Changelog:
- fix: https://github.com/zlib-ng/minizip-ng/pull/834
- fix: https://github.com/zlib-ng/minizip-ng/pull/832
- fix: https://github.com/zlib-ng/minizip-ng/pull/865
In other words:
- It fixes zipping files with `*` in the name. (old bug?)
- It fixes zipping files with `\` in the name. (regression in minizip 3.0.7 -- ZipArchive 2.5.3)
- It fixes unzipping files with `\` in the name. (old bug?)
=> Updating to minizip-ng 4.0.9

SSZipArchive/SSZipArchive.m
- revert #443 (adding explanations why)
- fix #449
=> revert "do not assume entries made on dos systems have utf-8 filename (#443)"
