ZipArchive/ZipArchive

SSZipArchive/SSZipArchive.h
SSZipArchive/SSZipArchive.m

I needed the ability to store files inside a folder in the zip. This was easy enough to do and works for me, so I thought I share it with you.

Add support for archives in folders

---

SSZipArchive/SSZipArchive.h
SSZipArchive/SSZipArchive.m

Reverts soffes/ssziparchive#129

Revert "Add support for archives in folders"

---

SSZipArchive.h
SSZipArchive.m

Added functionality to zip folder and maintains subfolder tree

folder and subfolder zip functionality

---

SSZipArchive.h

Add writeFileAtPath:withFileName: in SSZipArchive.h so that it can be called.

Add writeFileAtPath:withFileName: in SSZipArchive.h so that it can be called.

---

SSZipArchive/SSZipArchive.h
SSZipArchive/SSZipArchive.m

We needed the path of the extracted files inside a zip, so we added this delegate method.
Implements #101

Add delegate method with extracted file path

---

SSZipArchive.podspec

PR to fix the issue of previous PR with podspec pointing to a non-existing tag

fixed podspec pointing to non-existing tag in the main repo

---

ZipArchive/Main.m

Reverts ZipArchive/ZipArchive#189

Revert "Close file pointer after adding to archive"

---

SSZipArchive.podspec

Reverts ZipArchive/ZipArchive#187

Revert "Update SSZipArchive.podspec"

---

SSZipArchive/SSZipArchive.h

Updated `BOOL` getters for `open` and `close` properties.

Added getters.

---

SSZipArchive/Info.plist
SSZipArchive/ZipArchive.h
ZipArchive.xcodeproj/project.pbxproj
ZipArchive.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ZipArchive.xcodeproj/xcshareddata/xcschemes/ZipArchive.xcscheme

Created new project file that contains only one target and only one scheme for framework which is suitable for Carthage to build and integrate. Also added base header file and info.plist file for framework. Bundle identifier is same as in ObjectiveCExample

Added carthage support

---

.gitignore
README.md
SSZipArchive/SSZipArchive.h
SSZipArchive/ZipArchive.h
SwiftExample/Cartfile
SwiftExample/SwiftExample.xcodeproj/project.pbxproj
SwiftExample/SwiftExample/ViewController.swift
ZipArchive.xcodeproj/project.pbxproj
ZipArchive.xcodeproj/xcshareddata/xcschemes/ZipArchive-Mac.xcscheme
ZipArchive.xcodeproj/xcshareddata/xcschemes/ZipArchive-iOS.xcscheme

Fixes issue #226. Builds on top of #222.
To use this change until it is reviewed:
```
github "LootApp/ZipArchive" "mac-target"
```

Mac target added

---

SSZipArchive/SSZipArchive.h

See https://github.com/ZipArchive/ZipArchive/commit/8ba930ef4be56db977206f6ef90a30663960b877

Fixes broken commit

---

SSZipArchive/SSZipArchive.m

If ZipArchive is used to create zips in read-only contexts (like, for example, iOS action extensions), its attempts to create the `.DS_Store` files in empty directories will silently fail. As such, those directories will be pruned from the hierarchy. This PR fixes the issue by creating the .DS_Store file in user's temporary directory. We don't clean up the directory in the end, as `NSTemporaryDirectory()` is regularly cleaned by the OS and the `.DS_Store` files are absolutely minute.

Create the .DS_Store files in temp directory for read-only contexts

---

ObjectiveCExample/ObjectiveCExampleTests/SSZipArchiveTests.m
SSZipArchive/SSZipArchive.h
SSZipArchive/SSZipArchive.m

I added a function to check if a zip file is password protected. (plus a unit test)
It is based on this: http://stackoverflow.com/a/13937828

check if zip file is password protected

---

ObjectiveCExample/ObjectiveCExampleTests/SSZipArchiveTests.m
ObjectiveCExample/Podfile.lock
SSZipArchive/SSZipArchive.m

Hi!
It seems that I have found bug related to symlinked files. 
Tests were not able to reveal it, so I've updated them too.

Fix of symlinked files bug

---

SSZipArchive/SSZipArchive.m

Reverts ZipArchive/ZipArchive#281. Users reported breaking changes after this landed. Will test and re-add when resolved.

Revert "Extended to allow passing in directory or file to unzip to"

---

SSZipArchive/SSZipArchive.h
SSZipArchive/SSZipArchive.m
SSZipArchive/minizip/unzip.c
SSZipArchive/minizip/unzip.h

I guess this functionality could be an useful addition. Thanks

Added password validation & prevent stale file entries in case of invalid password

---

SSZipArchive/SSZipArchive.h
SSZipArchive/SSZipArchive.m

Reverts ZipArchive/ZipArchive#307
Tests did not pass after merge.

Revert "Added support for getting zip file creation progress."

---

SSZipArchive/SSZipArchive.m

- giving an NSError to completionHandler on failure
- always calling completionHandler

giving an NSError to completionHandler on failure

---

SSZipArchive/SSZipArchive.m

Use -fileSystemRepresentation for file names

---

ObjectiveCExample/Podfile.lock
SSZipArchive.podspec
SSZipArchive/minizip/crypt.c
SSZipArchive/minizip/crypt.h
SSZipArchive/minizip/minishared.c
SSZipArchive/minizip/minishared.h
SSZipArchive/minizip/unzip.c
SSZipArchive/minizip/zip.c
SwiftExample/Podfile.lock

fixes https://github.com/nmoinvaz/minizip/issues/123 (regression introduced with SSZipArchive 2.0.0)

Fix compatibility with 7-zip/WinRAR (regression in SSZipArchive 2.0.0)

---

ObjectiveCExample/ObjectiveCExampleTests/SSZipArchiveTests.m
SSZipArchive/SSZipArchive.m

fix #323
Needs testing for compatibility with other programs.

unicode passwords

---

SSZipArchive/SSZipArchive.m

Would need a unit test to be complete.

fix zipInfo:setDate: when currentCalendar was not gregorian

---

SSZipArchive/SSZipArchive.m

Improve #273 (=#269).
Fix #384.
Fix #315.
I want to do a few more testing, like to see if the fallback in base64 is working.

supporting encoding detection

---

ObjectiveCExample/ObjectiveCExampleTests/SSZipArchiveTests.m
SSZipArchive/minizip/unzip.c

compatibility with incorrect headers

---

SSZipArchive/SSZipArchive.m

support nested zip by calling fclose first

---

SSZipArchive/minizip/unzip.c
SSZipArchive/minizip/unzip.h

Fix https://github.com/nmoinvaz/minizip/issues/184

workaround incorrect file count

---

SSZipArchive/SSZipArchive.m

Filenames have been assumed utf-8 and only when decoding as such failed are other encodings taken into account. 
We check if a file entry is created on a dos system and if the "Language encoding flag" is cleared, we read filename as
"Code Page 437" text as described in:
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT Appendix D
This makes decoding of archives from WinZip with extended latin characters work better.

don't assume entries made from dos have utf-8 filename unless flag says so

---

SSZipArchive/SSZipArchive.m

I ran a Coverity analysis on ZipArchive, and it revealed a number of issues. This fixes ~4~ 19 of them.

Some analysis fixes

---

LICENSE.txt

Since I haven't been involved in this project since 2013, let's update the license :)

Remove me from license

---

.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
Example/Podfile.lock
Package.swift
README.md
Release-Instructions.md
SSZipArchive.podspec
SSZipArchive/SSZipArchive.m
SSZipArchive/SSZipCommon.h
SSZipArchive/minizip/mz.h
SSZipArchive/minizip/mz_compat.c
SSZipArchive/minizip/mz_compat.h
SSZipArchive/minizip/mz_crypt.c
SSZipArchive/minizip/mz_crypt_apple.c
SSZipArchive/minizip/mz_os.c
SSZipArchive/minizip/mz_os_posix.c
SSZipArchive/minizip/mz_strm_zlib.c
SSZipArchive/minizip/mz_zip.c
SSZipArchive/minizip/mz_zip.h
SSZipArchive/minizip/mz_zip_rw.c
ZipArchive.xcodeproj/project.pbxproj

Pretty big changes from our 2019 copy to current. Would appreciate some more eyes.

mz_compat updated to minizip 3.0.6

---

SSZipArchive/SSZipArchive.m

Fix #689
Fix #657
@andalman
@Shellylang

fix zip creation for file permissions and unicode symlinks

---

.github/workflows/actions.yml

Work-In-Progress attempting to address: https://github.com/ZipArchive/ZipArchive/actions/runs/11074275169/job/30772691087?pr=562

Fix GitHub actions

---

Example/SwiftExample_macOS/Base.lproj/Main.storyboard

"Certain autolayout constraint combinations may result in an appropriate layout in the current development language but will pose issues in other languages and regions."

Fix autolayout warning in sample project.

---

.github/workflows/actions.yml

macOS 12 isn't supported by GitHub anymore

Updating minimum GitHub action target

---

README.md

Link to potentially more active alternatives to ZipArchive.

link to ZipArchive alternatives

---

SSZipArchive/SSZipArchive.m

Fix setting directory file modification date
